### ISSUE TITLE
merge in our features?

### ISSUE THREAD

**Issue by lusis** [tinyspeck/chef-handler-slack#1]
We had this functionality already. Not sure if you want to merge in anything from it:

https://github.com/dcm-ops/chef-slack_handler

**Comment by dsmith** [comment]
Most certainly! The only reason why this repository existed was really just an exercise in how to incorporate Slack into a Chef handler. I also wanted to be able to install the handler via a Gem and there appeared to be no gems available for a Chef handler that reports to Slack.

We will probably end up using `dcm-ops` version of Chef's slack handler since it appears to be more rich in features.
